version = 1

[checks]
  [[checks.html]]
  [[checks.css]]


[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs",
    "angular"
  ]
