version = 1

[checks]
  [[checks.html]]
  check = ["html-001", "html-002", "html-003"]
  
  [[checks.css]]
  check = ["css-001", "css-002"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs",
    "angular"
  ]
